language: python
python:
  - "2.6"
  - "2.7"
services:
  - redis-server
before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
  - which thrift
before_script:
  - sudo echo "Asia/Seoul" > /etc/timezone
  - export TZ=Asia/Seoul
  - date
  - cp etc/arara_settings.py.sample etc/arara_settings.py
  - make
script: py.test arara/test
